### ISSUE TITLE
kerning for "P.D"

### ISSUE THREAD

**Issue by baltakatei** [hikikomori82/osifont#10]
## Description
Kerning rules for strings starting in `P.` or `P,` may cause intersections of `P` with subsequent glyphs.

## Environment
Debian 10 [LibreOffice](https://www.libreoffice.org/) 6.1.5.2
Debian 10 [Inkscape](https://inkscape.org/release/inkscape-0.92/) 0.92

## Expected Behavior
A string such as `P.D` should be wider than the string `PD`.

## Actual Behavior
The `.` glyph causes the entire string to be narrower.

## Steps to reproduce
1. Install `osifont.ttf` (e.g. Download `osifont.ttf` into `~/.local/fonts/`. Set permissions to 644 using `chmod 644 ~/.local/fonts/osifont.ttf` as directed by [Debian font install docs](https://wiki.debian.org/Fonts). Run `fc-cache` to make font available to applications (e.g. LibreOffice)).
3. Start up LibreOffice
4. Set font dropdown menu to `osifont`.
5. Type `PD`
6. Type `P.D`

## Demonstration of bug
- [LibreOffice example screenshot](https://reboil.com/res/2021/img/20211206T1838Z..osifont_kerning_bug_libreoffice_PD.png)
- [Inkscape example showing various other problematic combinations](https://reboil.com/res/2021/img/20211206T1808Z..osifont_kerning_bug_capital_p.png)

**Comment by hikikomori82** [comment]
Fixed on github

2021-12-06 19:47 GMT+01:00, baltakatei ***@***.***>:
