### ISSUE TITLE
it's not just russia that's using cyrillic?

### ISSUE THREAD

**Issue by alexmyczko** [hikikomori82/osifont#11]
so mind undoing the removal?

**Comment by hikikomori82** [comment]
These 2 characters are only used in Russian, Belorusian.

**Comment by janc13** [comment]
30% of the population in Ukraine has Russian as their mother tongue. And that includes Ukraine president Zelensky, as well as many in the Ukraine military & volunteer defence forces.

Please don’t help Russia’s claims that Russian-speaking people (in Ukraine & elsewhere) are being discriminated against with stupid actions like this…

**Comment by janc13** [comment]
(Maybe I should have used “actions without much overthought” instead of “stupid actions” there… 😉 )

**Comment by Sod-Almighty** [comment]
No, you were correct: It's a stupid action.

One tyrannical egomaniac decides to commit his country to a senseless and unjust invasion of another country (most wars are senseless and unjust, of course), and so the font creators break their own font "in protest".

Does this hurt Putin? No. He doesn't care. He is unaffected. His government almost certainly has the funds to buy professional CAD packages that come with paid fonts.

Who does this punitive action actually hurt? Hobbyists and enthusiasts. In Russia, Ukraine and probably several other places unrelated to the war. Many of these hobbyists probably oppose the war: I'm given to understand it wasn't a very popular move even in Russia itself.

Of course the creators of the font can do whatever they like. But it's still stupid, and punishes innocent hobbyists for the actions of a government that is in no way affected by the stupid action. Even if using a font as a political vehicle were an acceptable thing to do (it isn't), this "protest" was very badly thought-out and is aimed at entirely the wrong victims.
