### ISSUE TITLE
Monospace even thought it is set to Modern(Variable width)

### ISSUE THREAD

**Issue by tobiasfalk** [hikikomori82/osifont#12]
I discovered that the newest version of the font is monospace even thought it is set to Modern(variable width).
This problem is a bit more discussed in the [FreeCAD forum](https://forum.freecadweb.org/viewtopic.php?f=35&t=72561).
I tested it with a Linux(OpenSuse 15.3) and a Windows 10 PC and get the same results, I also tried changing the Element->Font Info->OS/2->Panose->Proportion Value to something different but this didn't change anything.

**Comment by hikikomori82** [comment]
Fixed in latest version (kerning was wrong)
