### ISSUE TITLE
How does the license affect programs that embed this font?

### ISSUE THREAD

**Issue by cesss** [hikikomori82/osifont#19]
The OFL SIL license allows a font to be embedded in a computer program, without any requirement on the license of the program (ie: the copyleft doesn't affect the program). How does the license of osifont behave regarding this? (you explicitly mention in the readme that one use case of the font is in CAD programs, so I guess this question is an important one).

**Comment by hikikomori82** [comment]
This font is primarily intended for open source CAD programs. I don't use any commercial CADs and therefore I don't care how it affects commercial CADs. If you want to know how it affects commercial CADs, hire a software lawyer and discuss it with him.
