### ISSUE TITLE
Font file differences between licences?

### ISSUE THREAD

**Issue by Denny-89** [hikikomori82/osifont#21]
Are there any physical differences between the ttf files? 

I'm no CAD developer, i just plan to use it for personal things like adding text on my own 3D printable models and wish to use the ttf file without the "missing features" if there are any.

**Comment by hikikomori82** [comment]
All 3 fonts are identical, the only difference is license.

**Comment by hikikomori82** [comment]
All 3 fonts are identical, the only difference is license.
