### ISSUE TITLE
Please confirm license for source file osifont.sfd

### ISSUE THREAD

**Issue by coldtobi** [hikikomori82/osifont#23]
Hi,

while packaging FreeCAD for Debian I cam across the [fonts-osifont](https://tracker.debian.org/fonts-osifont) package for Debian and found that the file osifont.sfd is not clearly licensed and to avoid DFSG problems I'm reaching out for clarifcation. This issue is tracked at [Debian Bug #1091082](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1091082)

IIUIC the license is applied when running generate.sh by replacing LICENSE_PLACEHOLDER in osifont.sfd. However this does not specify the license for this file, so I assume the license for this file is the three licenses options "ored", like 

    GNU GPL licence version 3 with font exception  OR
    GNU GPL licence version 2 with font exception OR
    GNU LGPL licence version 3 with font exception

I'd appreciate if you could confirm my understanding, so that I'll be able to fix the Debian bug.

TIA! (and many kudos for the font!)

**Comment by hikikomori82** [comment]
Yes, you can pick one of the 3 licenses, the script itself also have one of the three licenses

**Comment by coldtobi** [comment]
Many thanks for the clarification!
