### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by jonasstein** [hikikomori82/osifont#5]
the license files are missing in the repository

**Comment by hikikomori82** [comment]
You can download licences from internet

**Comment by jonasstein** [comment]
I understand the GPL differently, see: https://www.gnu.org/licenses/gpl-howto.html

> Add a COPYING file with a copy of the GNU GPL or GNU AGPL.
> Also add a COPYING.LESSER file with a copy of the GNU LGPL, if you use that.

Best, JS

**Comment by hikikomori82** [comment]
$ wget -qO - https://www.gnu.org/licenses/gpl-3.0.txt | grep COPYING | wc -l
(no matches)
$ wget -qO - https://www.gnu.org/licenses/gpl-2.0.txt | grep COPYING
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

Licence itself does not mention anywhere that it must be placed in file named "COPYING", thus it is not legally binding only "recommendation". Unless you show me lines FROM THE LICENCE ITSELF that clearly states that I MUST have file named "COPYING" to comply with licence, I will not add it.

**Comment by jonasstein** [comment]
IANAL, but I think the page is very clear about this by explaining 

> Here's a brief summary of what you need to do to release a program under one of our licenses:

There is no negative side effect either, but improper licensing makes it difficult to distribute your (very interesting) font.
https://bugs.gentoo.org/604322

**Comment by hikikomori82** [comment]
If you want COPYING file in your package add it yourself to your package.

**Comment by davelab6** [comment]
> you show me lines FROM THE LICENCE ITSELF that clearly states that I MUST have file named "COPYING" to comply with licence

Sure. The license says in the intro, bold emphasis mine, 

>> if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received.  You must make sure that they, too, receive or can get the source code.  And **you must show them these terms** so they know their rights

You must show them these terms. 

It continues, 

>> Developers that use the GNU GPL protect your rights with two steps: (1) assert copyright on the software, and (2) **offer you this License** giving you legal permission to copy, distribute and/or modify it.

You must offer users a copy of this license. 

Then Section 4 says

> give all recipients a copy of this License along with the Program.

You must give all recipients a copy of this License.

**Comment by hikikomori82** [comment]
> You must make sure that they, too, receive OR CAN GET the source code.
Case closed.

**Comment by davelab6** [comment]
That's about the source code; not about them knowing their rights, which is different, and what this issue is about.
