### ISSUE TITLE
Vertical font alignment?

### ISSUE THREAD

**Issue by AndreHorst** [hikikomori82/osifont#6]
I have the issue that the font is not vertically aligned correctly. Or is this a feature of the font philosophy? So, when using Gnuplot or LibreOffice, the font always seems to be have its vertical center anker at the very top (see image below).

![image](https://user-images.githubusercontent.com/25814609/32158987-af232354-bd4b-11e7-8e8d-66ee893c9dff.png)

Anyone has an idea to solve this?

**Comment by hikikomori82** [comment]
Works for me just fine in other programs, you have to ask gnuplot/libreoffice guys why is it doing it, i don't know.

**Comment by AndreHorst** [comment]
Okay, so with debian I have the following offset in vertical alignment:
![osifont_issue](https://user-images.githubusercontent.com/25814609/32160212-01913496-bd51-11e7-9d1a-69b69c3d463a.jpg)
So this is not the case for you system? Than it's a debian issue which would be sad.

**Comment by hikikomori82** [comment]
Well, in that case, I think it's program's fault because they should use baseline positioning, not top positioning.
