### ISSUE TITLE
Issues with Cyrillic

### ISSUE THREAD

**Issue by andrewshadura** [hikikomori82/osifont#7]
1) «з» is too tall, it shouldn’t be taller than any other lower case letter
2) «в» has the bottom part smaller than the top part, should be other way round
3) «ь» is not the same as «b», and should basically look the same as the left part of «ы»
4) «и»/«й» is too wide, should be the same width as «н»
5) «У»/«Ў» is too narrow, should be at least as wide as «П»

Also, one of the languages is named incorrectly, it’s Belarusian, not Belorussian.

**Comment by hikikomori82** [comment]
Slava Ukrajini. Belorussian is not supported language, never will be.

**Comment by andrewshadura** [comment]
Excuse me? Belarusians and Ukrainians are on the same side. Belarus is ruled by an oppressive government which imprisons and kills people of Belarus. Belarusians fight side by side with Ukrainians against Russian invasion. To suggest letters used by Belarusian language shouldn't be supported because we've been fighting dictatorship since 1996 is disrespectful and beyond offensive.

Besides, apart from one letter, the issues I described are valid also for Ukrainian.
